
// auth 
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAILURE = 'REGISTER_FAILURE';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

// patron
export const GET_PATRON_PROFILE ='GET_PATRON_PROFILE';
export const ADD_PATRON_PROFILE = 'ADD_PATRON_PROFILE';
export const UPDATE_PATRON_PROFILE = 'UPDATE_PATRON_PROFILE';
export const DELETE_PATRON_PROFILE = 'DELETE_PATRON_PROFILE';

// vendor
export const GET_PATRONS_PROFILES = 'GET_PATRONS_PROFILES';
export const GET_VENDORS_PROFILES = 'GET_VENDORS_PROFILES';
export const GET_VENDOR_PROFILE = 'GET_VENDOR_PROFILE';
export const ADD_VENDOR_PROFILE = 'ADD_VENDOR_PROFILE';
export const UPDATE_VENDOR_PROFILE = 'UPDATE_VENDOR_PROFILE';
export const DELETE_VENDOR_PROFILE = 'DELETE_VENDOR_PROFILE';

// product
export const GET_PRODUCTS_SUCCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_FAILURE = 'GET_PRODUCTS_FAILURE';
export const GET_PRODUCT_SUCCCESS = 'GET_PRODUCT_SUCCESS';
export const GET_PRODUCT_FAILURE = 'GET_PRODUCT_FAILURE';
export const ADD_PRODUCT = 'ADD_PRODUCT';
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
